<?php
namespace App\Entities;
class YoutubePlaylist extends \SWD\Entities\YoutubePlaylist{
    static function loadMetadata($m)
    {
        parent::__loadMetadata($m); // TODO: Change the autogenerated stub
    }
}